apiVersion: v1
entries:
  httpserver:
  - apiVersion: v2
    appVersion: 0.0.3
    created: "2022-12-19T21:30:23.009879+08:00"
    description: A Helm chart for Kubernetes
    digest: 38f25fa01778558948555904fe7a230b8c77068640ad6960bdab6ddf7f7127a2
    name: httpserver
    type: application
    urls:
    - https://xyang0917.github.io/httpserver/deploy/helm/repo/stable/httpserver-0.1.0.tgz
    version: 0.1.0
generated: "2022-12-19T21:30:23.009318+08:00"
